In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# 1. Create

In [ ]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [ ]:
data

array([[[0.48003108, 0.44146385, 0.80173342, 0.36955555],
        [0.36791853, 0.96672089, 0.02690897, 0.05000183],
        [0.51120249, 0.09960263, 0.78821282, 0.85545042]],

       [[0.67808393, 0.46217333, 0.80645816, 0.93515466],
        [0.92385328, 0.04500892, 0.83364112, 0.94561375],
        [0.356634  , 0.83439379, 0.82842758, 0.48934849]]])

In [ ]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [ ]:
type(arr)

numpy.ndarray

# 2. Read

In [ ]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [ ]:
types

dtype('float64')

In [ ]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [ ]:
singleval

0.480031081005698

In [ ]:
data

array([[[0.48003108, 0.44146385, 0.80173342, 0.36955555],
        [0.36791853, 0.96672089, 0.02690897, 0.05000183],
        [0.51120249, 0.09960263, 0.78821282, 0.85545042]],

       [[0.67808393, 0.46217333, 0.80645816, 0.93515466],
        [0.92385328, 0.04500892, 0.83364112, 0.94561375],
        [0.356634  , 0.83439379, 0.82842758, 0.48934849]]])

# 3. Update

In [ ]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [ ]:
list2

array([0.38704184, 0.53632305, 0.9944246 , 0.44505152, 0.64292829,
       0.30036371, 0.62623128, 0.98110138, 0.24716036, 0.10309413])

In [ ]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [ ]:
dot

2.9501773252530117

In [ ]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [ ]:
maxs

0.9300368518784375

In [ ]:
data

array([[[0.48003108, 0.44146385, 0.80173342, 0.36955555],
        [0.36791853, 0.96672089, 0.02690897, 0.05000183],
        [0.51120249, 0.09960263, 0.78821282, 0.85545042]],

       [[0.67808393, 0.46217333, 0.80645816, 0.93515466],
        [0.92385328, 0.04500892, 0.83364112, 0.94561375],
        [0.356634  , 0.83439379, 0.82842758, 0.48934849]]])

In [ ]:
data[0][0][0] = 700

In [ ]:
data

array([[[7.00000000e+02, 4.41463849e-01, 8.01733417e-01, 3.69555550e-01],
        [3.67918528e-01, 9.66720888e-01, 2.69089716e-02, 5.00018320e-02],
        [5.11202492e-01, 9.96026268e-02, 7.88212818e-01, 8.55450419e-01]],

       [[6.78083930e-01, 4.62173332e-01, 8.06458161e-01, 9.35154662e-01],
        [9.23853275e-01, 4.50089233e-02, 8.33641123e-01, 9.45613753e-01],
        [3.56634000e-01, 8.34393794e-01, 8.28427576e-01, 4.89348492e-01]]])

In [ ]:
data.sort()
data

array([[[3.69555550e-01, 4.41463849e-01, 8.01733417e-01, 7.00000000e+02],
        [2.69089716e-02, 5.00018320e-02, 3.67918528e-01, 9.66720888e-01],
        [9.96026268e-02, 5.11202492e-01, 7.88212818e-01, 8.55450419e-01]],

       [[4.62173332e-01, 6.78083930e-01, 8.06458161e-01, 9.35154662e-01],
        [4.50089233e-02, 8.33641123e-01, 9.23853275e-01, 9.45613753e-01],
        [3.56634000e-01, 4.89348492e-01, 8.28427576e-01, 8.34393794e-01]]])

In [ ]:
print(data.shape)

(2, 3, 4)


In [ ]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [ ]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [ ]:
data

array([[[3.69555550e-01, 4.41463849e-01, 8.01733417e-01, 7.00000000e+02,
         2.69089716e-02, 5.00018320e-02],
        [3.67918528e-01, 9.66720888e-01, 9.96026268e-02, 5.11202492e-01,
         7.88212818e-01, 8.55450419e-01]],

       [[4.62173332e-01, 6.78083930e-01, 8.06458161e-01, 9.35154662e-01,
         4.50089233e-02, 8.33641123e-01],
        [9.23853275e-01, 9.45613753e-01, 3.56634000e-01, 4.89348492e-01,
         8.28427576e-01, 8.34393794e-01]]])

In [ ]:
np.delete(data, 0, axis=1)

array([[[0.36791853, 0.96672089, 0.09960263, 0.51120249, 0.78821282,
         0.85545042]],

       [[0.92385328, 0.94561375, 0.356634  , 0.48934849, 0.82842758,
         0.83439379]]])

In [ ]:
np.save("new array", data)

In [ ]:
test = np.load("new array.npy")

In [ ]:
test

array([[[3.69555550e-01, 4.41463849e-01, 8.01733417e-01, 7.00000000e+02,
         2.69089716e-02, 5.00018320e-02],
        [3.67918528e-01, 9.66720888e-01, 9.96026268e-02, 5.11202492e-01,
         7.88212818e-01, 8.55450419e-01]],

       [[4.62173332e-01, 6.78083930e-01, 8.06458161e-01, 9.35154662e-01,
         4.50089233e-02, 8.33641123e-01],
        [9.23853275e-01, 9.45613753e-01, 3.56634000e-01, 4.89348492e-01,
         8.28427576e-01, 8.34393794e-01]]])